### ISSUE TITLE
Rebrand

### ISSUE THREAD

**Issue by tyler-hitzeman** [focus-launcher/focus-launcher-android#13]
Rebrand the old Siempo code with Focus Launcher and it's new logo (files attached).

Create a publishable package that we can use for the Play Store. 

This will help us get the app back on the Play Store. (Siempo was removed from the Play Store after it shut down in spring 2021) 

Remove contribution button
- We haven't set up a way for contributions yet. 
- Siempo's contribution page was closed, so when a user tries to contribute, they see an error saying "The item you requested is not available for purchase"
- Let's remove this for now to avoid confusion. I documented this in #16 so we can tackle it in the future.

Remove Tempo button
- Tempo is the name for the batching notifications feature from Siempo. It has always been buggy, and is even more so after Android's notification changes. After a brief test, I confirmed that it doesn't work for SMS messages, and probably many other scenarios. Let's disable it for this first version. I created #18  so we can revisit it later

Bonus points if you also:
- document things along the way to make it easier for others to contribute, per #5
- pick a JDK version and update #7 

[Focus Launcher Logo.zip](https://github.com/focus-launcher/focus-launcher-android/files/6758498/Focus.Launcher.Logo.zip)

**Comment by zed13** [comment]
I start to work on icon change. Found some texts in app with Siempo name. There is feedback email and home page reference. It would be great  if I have right variants for all strings:

app_name --> Siempo
title_siempoPermissions --> Siempo Permissions
title_siempoRestrictions --> Restrictions
title_siempoLocation --> Location
lock_screen_label --> SiempoLockScreeen
str_siemposettings --> Siempo Settings
msg_noti_service_dialog --> Siempo Notification service is not enabled. Please allow Siempo to access notification service
msg_overlay_settings --> Siempo needs overlay permission enabled mandatorily.
siempo_note --> Siempo Note
permission_siempo_alpha_title --> "Siempo is using following permissions\n"
permission_title --> "Please enable the following permission(s) to allow the Siempo to work correctly:"
to_help_you_storage --> "To help you understand your current phone habits, Siempo needs permission to store information on this device. We do not read your private files or collect information about files on your device."
lbl_purchaseSiempo --> Purchase Siempo
lbl_exitSiempo --> Exit Siempo services
lbl_updateEmailDescription --> Siempo will never email you unless you request support or opt-in.
lbl_switchSiempo --> Switch to another home app
lbl_analytics_description --> Help improve your Siempo experience by automatically sending analytics, diagnostics, and usage data to Siempo. 
feedback_email --> feedback@siempo.co
faqlink --> http://www.getsiempo.com/apps/android/beta/faq.htm
make_siempo_your_default_home_app --> Make Siempo your default home app:
flag_first_time_install --> When you flag an app, Siempo will gently discourage you from over-using it. We\'ve flagged some apps that most users say they want to use less.  You can change these flags now or later.
exiting_siempo --> Exiting Siempo
exiting_siempo_msg --> "Exiting does not impact your subscription status. To re-enable Siempo protections after exiting, launch the Siempo app at any time. "
would_you_like_to --> Would you like to make Siempo \nyour default Home app?
siempo_need_permission --> "Siempo needs your permission"
siempo_images --> Siempo images
contribute_to_siempo --> Contribute to Siempo
device_admin_not_enabled --> Siempo is not marked as Device Administrator. Please check Security settings and enable it.
admin_receiver_status_enabled --> Siempo is added as Device Administrator
admin_receiver_status_disabled --> Siempo is removed from Device Administrators list

**Comment by zed13** [comment]
Here 3 variants with different icon: white, original (black + blue) and blue. By default android studio creates launcher icon with a background. For higher android version the different backgrounds (circle or rectangle) is set.

[app_variants.zip](https://github.com/focus-launcher/focus-launcher-android/files/6787138/app_variants.zip)

**Comment by tyler-hitzeman** [comment]
- yes, replacing `Siempo` with `Focus Launcher` is great. 
- email is: focuslauncher@gmail.com
- Is it possible to omit the FAQ link? If not I'll add one to the website at: www.focuslauncher.io/faq. 
- We're not monitizing Focus Launcher, so this can be removed if it doesn't break anything`lbl_purchaseSiempo --> Purchase Siempo`

**Comment by tyler-hitzeman** [comment]
I prefer the `_original.apk`icon version -- it seems to stand out more than the others.

**Comment by zed13** [comment]
> 
> 
> I prefer the `_original.apk`icon version -- it seems to stand out more than the others.

So, be it.

**Comment by zed13** [comment]
When app launcher there is a logo shown on the first screen:
![image](https://user-images.githubusercontent.com/5735844/125160589-75041080-e186-11eb-943a-1c97cf23d5aa.png)
The text and the Siempo's log is the whole thing.
I could change it to this variant:
![image](https://user-images.githubusercontent.com/5735844/125160606-8f3dee80-e186-11eb-9557-6d0dd9da5dbb.png)
Or I could do this:
![image](https://user-images.githubusercontent.com/5735844/125160728-315dd680-e187-11eb-88ae-88c54bc017fc.png)


May be you have some logo for app with app's title?

**Comment by zed13** [comment]
Focus logo with bold text looks better:
![image](https://user-images.githubusercontent.com/5735844/125160941-29526680-e188-11eb-8ac0-6b530ef28501.png)

**Comment by tyler-hitzeman** [comment]
Awesome. I agree, the last one (with bold text and Focus Launcher to the right of the icon) looks the best. 

We don't currently have any additional logo variants or assets other than those attached to the top of this issue.
