### ISSUE TITLE
Rebrand Part II

### ISSUE THREAD

**Issue by tyler-hitzeman** [focus-launcher/focus-launcher-android#17]
These tasks are secondary and internal rebrands that follow up from #13. I broke them out into this issue because they're not critical to getting the app working or back out there. However, it'll make things easier for future maintainers once the code and these other aspects are migrated to the new 'Focus Launcher' verbiage & images

Replace Siempo verbiage in source code. Some examples:
- [x] Change `src/main/java/co/siempo` to something like `/src/main/java/io/focuslauncher` or `.../io/fl/` 
- [x] Update URL in `UpdateActivity.java`
- [x] Update 'Leave a review' link in the Help menu (currently goes to Siempo app)

**Comment by bhanup212** [comment]
These issues are fixed in last PR
