### ISSUE TITLE
Product Hunt Launch - February 10

### ISSUE THREAD

**Issue by tyler-hitzeman** [focus-launcher/focus-launcher-android#68]
The goal of this launch is to attract users and project contributors
⚫  = Ty
🟠  = Nick
🟣  = Sharan

### Before Launch
- [x] Schedule launch posts to: Twitter 🟣 
- [x]  Update website 🟣 
    - Add analytics
    - add play icon to bottom of page
    - Make more SEO-friendly (add keywords, etc)
    - link to GitHub roadmap and the redesign project board
    - remove leadership positions part
- [x]  Schedule launch date (Feb 10, 2022) 
- [x]  Draft email to community newsletter ⚫
- [x]  setup new project board for public access            
- [x]  Update GitHub README.md
- [x]  Update icons so it works on dark mode
- [x]  Assemble assets
- [x]  Update Play store listing
- [x]  Create task board
- [x]  Write Product Hunt description

### During Launch
- [ ]  Respond to comments on PH and Twitter 🟣  ⚫   🟠   
- [x] Add [PH badge](https://help.producthunt.com/en/articles/2731371-how-to-add-a-product-hunt-badge-to-your-website) to website ⚫ 
- [x]  Send email to FL subscribers ⚫ 
    - Can't schedule it to auto-send because we don't have the link to our PH until it launches
- [ ]  Announce launch on these sites:
    - [x]  Hackers News ⚫ 
    - [ ]  Reddit 🟠 
    - [ ] Indie Hackers 🟠 
    - { any other relevant site} 

### After Launch
- [x] Post thank-you notes and summary of how it went [TBD] 
    - Twitter
    - Reddit
    - Indie Hackers
    - CHT Forum

**Comment by tyler-hitzeman** [comment]
I've assigned myself, but I'm happy to get some help with those tasks or with responding to messages on/after launch day

**Comment by sharansalian** [comment]
@tyler-hitzeman I will be happy to help.

**Comment by tyler-dane** [comment]
@sharansalian great! Which of those subtasks would you like to help with? And what time zone are you in? Any days in January of February that you definitely couldn't be available? (That'll help me know how to coordinate the launch day timing).

**Comment by sharansalian** [comment]
Happy New year! @tyler-hitzeman 

I'm not sure why I never got a notification for the above mention & I took a look at this just now. I'm in IST timezone. I want to look into the marketing efforts, but take something minimal as a first task, maybe website or twitter related.

**Comment by NickIkenma** [comment]
> Anyone interested in joining the launch team? I've assigned myself, but I'm happy to get some help with those tasks or with responding to messages on/after launch day

Yeah. I'd love to help.

**Comment by tyler-dane** [comment]
Great! I'll work on dividing the tasks and assembling the info you'll need (website, twitter logins, etc) during our next co-working session (see Discord) and follow-up afterwards. If you can make it to the co-working session, we can also coordinate those things in real-time.

**Comment by NickIkenma** [comment]
Alright Ty
 Thanks.

**Comment by tyler-dane** [comment]
![Screen Shot 2022-02-12 at 10 03 05 PM](https://user-images.githubusercontent.com/30163055/153738175-305fd247-5292-4e99-9af0-6a870a73b4c8.png)
![Screen Shot 2022-02-12 at 10 03 31 PM](https://user-images.githubusercontent.com/30163055/153738176-2df2bd50-5d31-4791-8ee9-4f43076594fc.png)

The Launch didn't make as big of a splash compared to other products on that day, but we did get a few new users. Thanks for the help and shoutout, @NickIkenma
