### ISSUE TITLE
Discuss JDK Version to use

### ISSUE THREAD

**Issue by ghost** [focus-launcher/focus-launcher-android#7]
This would impact how many people would use the software along with the ease of creating the software.

**Comment by mllewellynjones** [comment]
I'd probably opt for version 11 as the latest LTS, but equally happy for you to make a different decision if going with a later version gives us some needed capability we won't get otherwise.

**Comment by tyler-hitzeman** [comment]
Denis (SneakyDroid) is working on getting the app back in the Play Store and I believe he also wants the latest LTS. Keep an eye on a PR from him for #13 for confirmation.
